### ISSUE TITLE
improve zoom bahavior

### ISSUE THREAD

**Issue by Klumbumbus** [KaartGroup/highwayNameModificationJOSMPlugin#1]
This is a nice plugin!
One thing that I don't like is that the mapview zooms so far in to the address, sometimes even the street is out of the mapview. Since you can't zoom when the question window is open you quickly loose orientation.
I think it would be better if the zoom is set to 2-3 steps lower, or if the mapview zooms to the whole street and stays constant and then only the selection of the addresses jumps around (however this could be bad for very long streets as the zoom would maybe be too low then).

**Comment by taylorsmock** [comment]
I intended to zoom to the building and the nearest segment of the road, but I kept getting exceptions. Its on my TODO list though.
